version: '3.8'

services:
  app:
    build:
      context: ./simple-cdn-server
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./uploads:/app/uploads
    environment:
      NODE_ENV: development
